version: "3.5"
services:
  preprod-postgresql:
    container_name: preprod-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - preprod-temporal-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  preprod-temporal:
    container_name: preprod-temporal
    depends_on:
      - preprod-postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - preprod-temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap
  preprod-temporal-admin-tools:
    container_name: preprod-temporal-admin-tools
    depends_on:
      - preprod-temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=preprod-temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    networks:
      - preprod-temporal-network
    stdin_open: true
    tty: true
  preprod-temporal-ui:
    container_name: preprod-temporal-ui
    depends_on:
      - preprod-temporal
    environment:
      - TEMPORAL_ADDRESS=preprod-temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - preprod-temporal-network
    ports:
      - 8080:8080
networks:
  preprod-temporal-network:
    driver: bridge
    name: preprod-temporal-network
