---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: temporal-pv-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/Dev/deploy-src/dev-temporal-postgress
    server: 10.201.2.2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: temporal-pv-dev-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi