---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: temporal-pv-preprod
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/Preprod/deploy-src/preprod-temporal-postgress
    server: 10.201.2.2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: temporal-pv-preprod-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 30Gi